# Generated by Django 5.0.2 on 2024-02-16 11:03

import django.db.models.deletion
import products.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mamlakat',
                'verbose_name_plural': 'Mamlakatlar',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nomi')),
                ('photo1', models.FileField(upload_to='subcategory', validators=[products.shared.validators.validate_image], verbose_name='1 - Rasm')),
                ('photo2', models.FileField(upload_to='subcategory', validators=[products.shared.validators.validate_image], verbose_name='2 - Rasm')),
                ('photo3', models.FileField(upload_to='subcategory', validators=[products.shared.validators.validate_image], verbose_name='3 - Rasm')),
                ('photo4', models.FileField(upload_to='subcategory', validators=[products.shared.validators.validate_image], verbose_name='4 - Rasm')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tola_turi', models.CharField(max_length=128, verbose_name='Tola turi')),
                ('zichligi', models.FloatField(verbose_name='Zichligi')),
                ('vorsi', models.FloatField(verbose_name='Vorsi balandligi')),
                ('ranglari', models.CharField(max_length=255, verbose_name='Ranglari')),
                ('narhi', models.FloatField(verbose_name='Narxi m2')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Mamlakat')),
            ],
            options={
                'verbose_name': 'Kolleksiya',
                'verbose_name_plural': 'Kolleksiyalar',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='products', validators=[products.shared.validators.validate_image], verbose_name='Rasm')),
                ('style', models.CharField(max_length=128, verbose_name='Stili')),
                ('forma', models.CharField(max_length=128, verbose_name='Formasi')),
                ('boyi', models.FloatField(verbose_name="Bo'yi")),
                ('eni', models.FloatField(verbose_name='Eni')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('nasiya', models.BooleanField(default=False, verbose_name='Nasiya savdo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Davlati')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='SubKategoria')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['country', 'created_at'],
            },
        ),
    ]
